title = "My Site"
baseURL = "https://example.org/"
theme = "hextra"

[[module.imports]]
# path = "github.com/imfing/hextra"

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
noClasses = false

[[menu.main]]
name = "Docs"
pageRef = "/docs"
weight = 1

[[menu.main]]
name = "About"
pageRef = "/about"
weight = 2

[[menu.main]]
name = "Contact ↗"
url = "https://github.com/imfing"
weight = 3

[[menu.main]]
name = "Search"
weight = 4

  [menu.main.params]
  type = "search"

[[menu.main]]
name = "GitHub"
weight = 5
url = "https://github.com/imfing/hextra-starter-template"

  [menu.main.params]
  icon = "github"

[[menu.main]]
name = "Twitter"
weight = 6
url = "https://twitter.com/"

  [menu.main.params]
  icon = "x-twitter"

[params.navbar]
displayTitle = true
displayLogo = false

[params.footer]
displayCopyright = false
displayPoweredBy = true

[params.editURL]
enable = true
base = "https://github.com/imfing/hextra-starter-template/edit/main/content"
