title = "战魂de小窝"
baseURL = "https://example.org/"
theme = "hextra"

[[module.imports]]
path = "github.com/imfing/hextra"

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
noClasses = false

[[menu.main]]
name = "Docs"
pageRef = "/docs"
weight = 1

[[menu.main]]
name = "Posts"
pageRef = "/posts"
weight = 2

[[menu.main]]
name = "About"
pageRef = "/about"
weight = 3

[[menu.main]]
name = "Contact ↗"
url = "https://github.com/imfing"
weight = 4

[[menu.main]]
name = "Search"
weight = 5

  [menu.main.params]
  type = "search"

[[menu.main]]
name = "GitHub"
weight = 6
url = "https://github.com/ybcjcc/etcdv"

  [menu.main.params]
  icon = "github"

# [[menu.main]]
# name = "Twitter"
# weight = 7
# url = "https://twitter.com/"

#   [menu.main.params]
#   icon = "x-twitter"

[params.navbar]
displayTitle = true
displayLogo = false

[params.footer]
enable = true
displayCopyright = false
displayPoweredBy = true
width =  'normal'

[params.editURL]
enable = true
base = "https://github.com/imfing/hextra-starter-template/edit/main/content"
